### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by FinnFrotscher** [dgrunwald/rust-cpython#293]
I run this little snipped
```rust
    let code_input = format!("def sum(a, b):\n  return a + b");
    let code_test = format!("\nresult = sum(1, 2)\nprint(result)",);
    let code = format!(
        r#"{}
{}"#,
        code_input, code_test
    );

    let result: Result<PyObject, PyErr> = py.eval(&code, None, None);

    println!("CODE: \n{}", code);
    println!("OUTPUT: \n{result:#?}\n");
```

And this is the result:
```
CODE: 
def sum(a, b):
  return a + b

result = sum(1, 2)
print(result)

OUTPUT: 
Err(
    PyErr {
        ptype: <class 'SyntaxError'>,
        pvalue: Some(
            ('invalid syntax', ('<string>', 1, 1, 'def sum(a, b):\n', 1, 4)),
        ),
        ptraceback: None,
    },
)

```

Where is the invalid syntax coming from?
if i copy paste the code into a python repl, it executes.

```python
def sum(a, b):
  return a + b

result = sum(1, 2)
print(result)
```

**Comment by ssokolow** [comment]
Python has a distinction between `eval` and `exec`, with the former only accepting expressions, not statements.

This is the REPL equivalent to what you asked rust-cpython to do:

```
>>> eval("""def sum(a, b):
...   return a + b
... 
... result = sum(1, 2)
... print(result)""")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<string>", line 1
    def sum(a, b):
    ^
SyntaxError: invalid syntax
```

I follow the [extend, don't embed](https://web.archive.org/web/20130113104244/http://twistedmatrix.com/users/glyph/rant/extendit.html) philosophy for combining Python with other languages, so, off the top of my head, I don't know how to exec.

**Comment by FinnFrotscher** [comment]
`Python::run` is indeed executing, thank you. 
But another problem pops up. The value is just printed to the console.
The signature is `let result: Result<(), PyErr> = py.run(&code, None, None);`
No return value. any idea off the top off your head how to capture that?
