### ISSUE TITLE
Python 3.12 support

### ISSUE THREAD

**Issue by decathorpe** [dgrunwald/rust-cpython#294]
I'm maintaining packages for the python3-sys and cpython crates for Fedora Linux, where they are currently used to build the Rust extension for mercurial. I've been trying to get the crates to work with Python 3.12 (our development branch recently switched to Python 3.12 beta 3).

First of all, the `_PyUnicode_READY` function was removed in Python 3.12, so it probably needs to be gated behind a `#[cfg(not(Py_3_12))]` attribute in the python3-sys crate. The `ready` attribute for these objects has been removed, so the check whether a string is "ready" can be dropped from the `PyString::data_impl` method entirely.

I can submit a PR with these initial changes, if it helps. They at least make the two crates *compile* against Python 3.12. But even so, they only reveal that there are some test failures with Python 3.12 that I don't know how to debug. Some of these might be caused by changes to the PyUnicodeObject.state bitfield in Python 3.12, but I'm not sure about that. But I think it is likely that the bitfield access offsets will need to be updated, since a similar change was necessary in pyo3.

```
---- objectprotocol::test::test_debug_string stdout ----
thread 'objectprotocol::test::test_debug_string' panicked at 'assertion failed: `(left == right)`
  left: `"'\0__\0\0\0\0\0"`,
 right: `"'Hello\\n'"`', src/objectprotocol.rs:371:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- objectprotocol::test::test_display_string stdout ----
thread 'objectprotocol::test::test_display_string' panicked at 'assertion failed: `(left == right)`
  left: `"\0\0\0\0\0\0"`,
 right: `"Hello\n"`', src/objectprotocol.rs:379:9

---- objects::string::test::test_extract_lone_surrogate stdout ----
thread 'objects::string::test::test_extract_lone_surrogate' panicked at 'assertion failed: `(left == right)`
  left: `[120, 61, 55296]`,
 right: `[0, 43819, 32644]`', src/objects/string.rs:642:17

---- objects::string::test::test_extract_lone_surrogate_lossy stdout ----
thread 'objects::string::test::test_extract_lone_surrogate_lossy' panicked at 'assertion failed: `(left == right)`
  left: `"x=�"`,
 right: `"\0ꬫ羄"`', src/objects/string.rs:659:9

---- objects::string::test::test_extract_umlaut stdout ----
thread 'objects::string::test::test_extract_umlaut' panicked at 'assertion failed: `(left == right)`
  left: `[120, 61, 228]`,
 right: `[96, 186, 92]`', src/objects/string.rs:624:17

---- binary_arithmetic stdout ----
thread 'binary_arithmetic' panicked at 'assert c + c == 'BA + BA': PyErr { ptype: AssertionError'>ì, pvalue: Some(nError()), ptraceback: Some(ck object at 0x7f92a00fa380>	`å ) }', tests/test_class.rs:871:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

---- number_extensions stdout ----
thread 'number_extensions' panicked at 'assert c % 1 == 'BA % 1': PyErr { ptype: AssertionError'>¢, pvalue: Some(nError()d")), ptraceback: Some(ck object at 0x7f92a00fbb40>	PÃ ) }', tests/test_class.rs:1411:5

---- python3_numbers stdout ----
thread 'python3_numbers' panicked at 'assert c @ c == 'BA @ BA': PyErr { ptype: AssertionError'>¢, pvalue: Some(nError()), ptraceback: Some(ck object at 0x7f92a00fbf80>	pÆ ) }', tests/test_class.rs:1452:5

---- rich_comparisons stdout ----
thread 'rich_comparisons' panicked at 'assert (c < c) == 'RC < RC': PyErr { ptype: AssertionError'>ì¢, pvalue: Some(nError()), ptraceback: Some(ck object at 0x7f92a0120100>	pË ) }', tests/test_class.rs:928:5

---- panicking stdout ----
thread 'panicking' panicked at 'panicking because reasons', tests/test_function.rs:190:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'panicking' panicked at 'assertion failed: `(left == right)`
  left: `"ic: panicking because reasons\0\0\0\u{1}\0\0\0\0"`,
 right: `"Rust panic: panicking because reasons"`', tests/test_function.rs:197:5
```

Tests run on `x86_64-unknown-linux-gnu` against Python 3.12b3. There are likely even more errors on other architectures (like big-endian System Z, which is already broken: #265 ).

**Comment by dgrunwald** [comment]
In the past, I diffed the Python 3.10 headers against the 3.11 headers, in order to find all relevant changes where we might need adjustment.
Unfortunately I won't have the time available to do that for 3.12.
